server: 
  port: 9003
spring: 
  application:  
    name: qa-community #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.105.58:3306/community_qa?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
